/*********************************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2013, Commonplace Robotics GmbH
 *  http://www.commonplacerobotics.com
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name Commonplace Robotics nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 *********************************************************************/
// Created on: 	Jan 12th, 2013
// Last Update:	Jan 21st, 2013


#ifndef cpr_robots_driver_teleop_keyboard_H
#define cpr_robots_driver_teleop_keyboard_H

#include <termios.h>
#include <signal.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include <boost/asio.hpp>
#include <boost/filesystem.hpp>
#include <boost/thread.hpp>

#include <ros/ros.h>
#include <geometry_msgs/Twist.h>


namespace cpr_robots{



//* Teleop keyboard class
/**
* This class starts a thread with a loop that waits for keyboard 
* input. When the user presses one of the keys ws, ad or qe 
* the tx, ty or rz velocities for the Slider platform are stored.
* The communication loop can get these via the getVelocities function.
*/
class CPRTeleopKeyboard{

	private:

	

	public:
	CPRTeleopKeyboard();
	~CPRTeleopKeyboard();

	/*!
    	* \brief	General initialization 
	* Starts the keyboardLoop thread
	*/
	int init();

	/*!
    	* \brief 	Thread to read the keys
    	* This loop is started as an seperate thread to read the keyboard while 
	* the main loop can communicate with the hardware
	*/	
	void keyboardLoop();
	
	/*!
    	* \brief 	Provides the velocities generated by the pressed keys
    	* Called by the main loop. Forwards linear.x and y and angular.z for the Slider platform. 
	* The further fields are zero.
    	* \param t      The velocities are written in t
	*/void getVelocities(geometry_msgs::Twist *t);

	geometry_msgs::Twist cmd_twist_internal;	/**< internal storage */

};



}



#endif
